CREATE TABLE T_GEND_UBIGEO_SOCIOECONOMICO
(
  OBJECTID                        INTEGER       NOT NULL,
  ID_UBIGEO_INEI                  VARCHAR2(255 BYTE),
  POBLACION                       NUMBER(38,8),
  INDICE_CARENCIAS                NUMBER(38,8),
  QUINTIL_INDICE_CARENCIAS        NUMBER(38,8),
  PCT_POBLACION_SIN_AGUA          NUMBER(38,8),
  PCT_POBLACION_SIN_DESAG_LETRIN  NUMBER(38,8),
  PCT_POBLACION_SIN_ELECTRIC      NUMBER(38,8),
  PCT_TASA_ANALFAB_MUJERES        NUMBER(38,8),
  PCT_NINOS_0_12_ANOS             NUMBER(38,8),
  PCT_TASA_DESNUTRIC              NUMBER(38,8)
)
TABLESPACE TS_DATA
PCTUSED    0
PCTFREE    0
INITRANS   4
MAXTRANS   255
STORAGE    (
            INITIAL          192K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX I34ID_UBIGEO_INE ON T_GEND_UBIGEO_SOCIOECONOMICO
(ID_UBIGEO_INEI)
NOLOGGING
TABLESPACE TS_DATA
PCTFREE    0
INITRANS   4
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX R70_SDE_ROWID_UK ON T_GEND_UBIGEO_SOCIOECONOMICO
(OBJECTID)
NOLOGGING
TABLESPACE TS_DATA
PCTFREE    0
INITRANS   4
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


GRANT SELECT ON T_GEND_UBIGEO_SOCIOECONOMICO TO R_INACC_CONSULTA;

GRANT SELECT ON T_GEND_UBIGEO_SOCIOECONOMICO TO R_SIG_CONSULTA;

GRANT DELETE, INSERT, SELECT, UPDATE ON T_GEND_UBIGEO_SOCIOECONOMICO TO R_SIG_EDITOR;

GRANT SELECT ON T_GEND_UBIGEO_SOCIOECONOMICO TO R_SIG_EDITOR_DGAAM;

GRANT SELECT ON T_GEND_UBIGEO_SOCIOECONOMICO TO R_SIG_EDITOR_DGE;

GRANT SELECT ON T_GEND_UBIGEO_SOCIOECONOMICO TO R_SIG_EDITOR_DGH;

GRANT SELECT ON T_GEND_UBIGEO_SOCIOECONOMICO TO R_SIG_EDITOR_DGM;

GRANT SELECT ON T_GEND_UBIGEO_SOCIOECONOMICO TO R_SIMEM_CONSULTA;

GRANT DELETE, INSERT, SELECT, UPDATE ON T_GEND_UBIGEO_SOCIOECONOMICO TO R_SIMEM_MNTO;
