CREATE TABLE T_GENL_UBIGEO_INEI
(
  ID_UBIGEO_INEI  CHAR(6 BYTE)                  NOT NULL,
  DEPARTAMENTO    VARCHAR2(60 BYTE)             NOT NULL,
  PROVINCIA       VARCHAR2(60 BYTE)             NOT NULL,
  DISTRITO        VARCHAR2(60 BYTE)             NOT NULL,
  FLG_ESTADO      CHAR(1 BYTE)                  DEFAULT 1,
  USU_INGRESO     VARCHAR2(20 BYTE)             DEFAULT USER,
  FEC_INGRESO     DATE                          DEFAULT SYSDATE,
  USU_MODIFICA    VARCHAR2(20 BYTE)             DEFAULT USER,
  FEC_MODIFICA    DATE                          DEFAULT SYSDATE,
  GEOMETRY        MDSYS.SDO_GEOMETRY,
  SDE_ID          NUMBER                        NOT NULL
)
COLUMN GEOMETRY NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE TS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          3M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB ("GEOMETRY"."SDO_ORDINATES") STORE AS 
      ( TABLESPACE  TS_DATA 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  10
        CACHE
        INDEX       (
          TABLESPACE TS_DATA
          STORAGE    (
                      INITIAL          64K
                      NEXT             1
                      MINEXTENTS       1
                      MAXEXTENTS       UNLIMITED
                      PCTINCREASE      0
                      BUFFER_POOL      DEFAULT
                     ))
        STORAGE    (
                    INITIAL          64K
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
  LOB ("GEOMETRY"."SDO_ELEM_INFO") STORE AS 
      ( TABLESPACE  TS_DATA 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  10
        CACHE
        INDEX       (
          TABLESPACE TS_DATA
          STORAGE    (
                      INITIAL          64K
                      NEXT             1
                      MINEXTENTS       1
                      MAXEXTENTS       UNLIMITED
                      PCTINCREASE      0
                      BUFFER_POOL      DEFAULT
                     ))
        STORAGE    (
                    INITIAL          64K
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE T_GENL_UBIGEO_INEI IS 'Ubicación geográfica INEI';

COMMENT ON COLUMN T_GENL_UBIGEO_INEI.ID_UBIGEO_INEI IS 'ID de ubicación geográfica INEI';

COMMENT ON COLUMN T_GENL_UBIGEO_INEI.DEPARTAMENTO IS 'Nombre de departamento';

COMMENT ON COLUMN T_GENL_UBIGEO_INEI.PROVINCIA IS 'Nombre de provincia';

COMMENT ON COLUMN T_GENL_UBIGEO_INEI.DISTRITO IS 'Nombre de distrito';

COMMENT ON COLUMN T_GENL_UBIGEO_INEI.FLG_ESTADO IS '1 Vigente, 0 No Vigente';

COMMENT ON COLUMN T_GENL_UBIGEO_INEI.USU_INGRESO IS 'Usuario de ingreso';

COMMENT ON COLUMN T_GENL_UBIGEO_INEI.FEC_INGRESO IS 'Fecha de ingreso';

COMMENT ON COLUMN T_GENL_UBIGEO_INEI.USU_MODIFICA IS 'Usuario de última modificación';

COMMENT ON COLUMN T_GENL_UBIGEO_INEI.FEC_MODIFICA IS 'Fecha de última modificación';


CREATE INDEX IS_GENL_UBIGEO_INEI ON T_GENL_UBIGEO_INEI
(GEOMETRY)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
NOPARALLEL;


CREATE UNIQUE INDEX I_GENL_UBIGEO_INEI_SDE ON T_GENL_UBIGEO_INEI
(SDE_ID)
LOGGING
TABLESPACE TS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX P_GENL_UBIGEO_INEI ON T_GENL_UBIGEO_INEI
(ID_UBIGEO_INEI)
LOGGING
TABLESPACE TS_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE T_GENL_UBIGEO_INEI ADD (
  CONSTRAINT VAL_BOOLEAN881
 CHECK ("FLG_ESTADO" IN (1, 0)),
  CONSTRAINT P_GENL_UBIGEO_INEI
 PRIMARY KEY
 (ID_UBIGEO_INEI)
    USING INDEX 
    TABLESPACE TS_IDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          128K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT SELECT ON T_GENL_UBIGEO_INEI TO CONSULTA;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO DB_ACT_SIMEM;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON T_GENL_UBIGEO_INEI TO DESA WITH GRANT OPTION;

GRANT REFERENCES, SELECT ON T_GENL_UBIGEO_INEI TO DGAAM WITH GRANT OPTION;
GRANT ALTER, DELETE, INDEX, INSERT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON T_GENL_UBIGEO_INEI TO DGAAM;

GRANT REFERENCES, SELECT ON T_GENL_UBIGEO_INEI TO DGAAME;

GRANT REFERENCES ON T_GENL_UBIGEO_INEI TO DGAAMI WITH GRANT OPTION;
GRANT SELECT ON T_GENL_UBIGEO_INEI TO DGAAMI;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO DGAAMW WITH GRANT OPTION;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO DGM WITH GRANT OPTION;
GRANT REFERENCES ON T_GENL_UBIGEO_INEI TO DGM;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO DGMW;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO DGM_COM;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO DGM_CONSULTA;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO DGM_CONSULTA_AMB;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO DGM_PPM;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO INACC WITH GRANT OPTION;

GRANT REFERENCES, SELECT ON T_GENL_UBIGEO_INEI TO OGGS WITH GRANT OPTION;

GRANT REFERENCES, SELECT ON T_GENL_UBIGEO_INEI TO OGGSW;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO R_DGM_MNTO;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO R_INACC_CONSULTA;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO R_OGGS_CONSULTA;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO R_OGGS_MNTO;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO R_SDGH_CONSULTA;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO R_SDGH_MNTO;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO R_SIEME_MNTO;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO R_SIG_CONSULTA;

GRANT DELETE, INSERT, SELECT, UPDATE ON T_GENL_UBIGEO_INEI TO R_SIG_EDITOR;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO R_SIG_EDITOR_DGAAM;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO R_SIG_EDITOR_DGE;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO R_SIG_EDITOR_DGH;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO R_SIG_EDITOR_DGM;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO R_SIMEM_CONSULTA;

GRANT DELETE, INSERT, SELECT, UPDATE ON T_GENL_UBIGEO_INEI TO R_SIMEM_MNTO;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO SDE;

GRANT REFERENCES, SELECT ON T_GENL_UBIGEO_INEI TO SDGH WITH GRANT OPTION;

GRANT REFERENCES, SELECT ON T_GENL_UBIGEO_INEI TO SDGH1 WITH GRANT OPTION;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO SIEME WITH GRANT OPTION;

GRANT SELECT ON T_GENL_UBIGEO_INEI TO SIMEM_BI WITH GRANT OPTION;
